<?php
/**
 * Seed-Pack: content-types (Recovery-/Bootstrap-Import-Set).
 *
 * MASCHINELL EXPORTIERT aus dem Live-Store der alkipedia-Staging (2026-07-08) —
 * kein manuelles Abtippen (BRIEF § 4.4-Datenqualität). Gefrorenes, NICHT auto-
 * registriertes Import-Set der 3 alkipedia-CPTs + 3 Taxonomien, args-treu.
 *
 * Nutzung ausschließlich durch den Importer (Seed-Restore, § 3.4) — die Provider
 * lesen es NIE direkt. Die Provider registrieren nur aus dem DB-Store (Invariante
 * § 3.3). Bei späterer Arg-Drift ist der Store die Wahrheit; der Seed ist der
 * Recovery-Boden, überschreibt nie automatisch.
 *
 * @package Depeur\Food\Modules\ContentTypes
 * @license GPL-2.0-or-later
 */

// Kein direkter Aufruf.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'version' => 1,
	'post_types' => 
	array(
		'bar-equipment' => 
		array(
			'labels' => 
			array(
				'name' => 'Bar Equipment',
				'singular_name' => 'Bar Equipment',
				'add_new' => 'Neu',
				'add_new_item' => 'Neue Bar Equipment hinzufügen',
				'edit_item' => 'Bar Equipment bearbeiten',
				'new_item' => 'Bar Equipment hinzufügen',
				'view_item' => 'Bar Equipment anzeigen',
				'view_items' => 'Bar Equipment anzeigen',
				'search_items' => 'Bar Equipment durchsuchen',
				'not_found' => 'No Bar Equipment found',
				'not_found_in_trash' => 'No Bar Equipment found in trash',
				'parent_item_colon' => 'Übergeordnet Bar Equipment:',
				'all_items' => 'Alle Equipment Einträge',
				'archives' => 'Bar Equipment archives',
				'attributes' => 'Bar Equipment attributes',
				'insert_into_item' => 'Insert into Bar Equipment',
				'uploaded_to_this_item' => 'Upload to this Bar Equipment',
				'featured_image' => 'Featured image for this Bar Equipment',
				'set_featured_image' => 'Set featured image for this Bar Equipment',
				'remove_featured_image' => 'Remove featured image for this Bar Equipment',
				'use_featured_image' => 'Use as featured image for this Bar Equipment',
				'filter_items_list' => 'Filter Bar Equipment list',
				'filter_by_date' => 'Nach Datum filtern',
				'items_list_navigation' => 'Bar Equipment list navigation',
				'items_list' => 'Bar Equipment list',
				'item_published' => 'Bar Equipment published',
				'item_published_privately' => 'Bar Equipment published privately.',
				'item_reverted_to_draft' => 'Bar Equipment reverted to draft.',
				'item_trashed' => 'Die Seite wurde in den Papierkorb verschoben.',
				'item_scheduled' => 'Bar Equipment scheduled',
				'item_updated' => 'Bar Equipment updated.',
				'item_link' => 'Seitenlink',
				'item_link_description' => 'Ein Link zu einer Seite.',
				'menu_name' => 'Equipment',
				'parent' => 'Übergeordnet Bar Equipment:',
				'name_admin_bar' => 'Bar Equipment',
				'template_name' => 'Einzelnes Element: Bar Equipment',
			),
			'description' => '',
			'public' => true,
			'publicly_queryable' => true,
			'exclude_from_search' => false,
			'hierarchical' => true,
			'show_ui' => true,
			'show_in_menu' => true,
			'show_in_nav_menus' => true,
			'show_in_admin_bar' => true,
			'show_in_rest' => true,
			'rest_base' => false,
			'rest_namespace' => 'wp/v2',
			'menu_position' => 6,
			'menu_icon' => 'dashicons-admin-post',
			'capability_type' => 'post',
			'map_meta_cap' => true,
			'supports' => 
			array(
				0 => 'title',
				1 => 'editor',
				2 => 'thumbnail',
				3 => 'comments',
				4 => 'author',
				5 => 'custom-fields',
				6 => 'autosave',
			),
			'has_archive' => true,
			'rewrite' => 
			array(
				'feeds' => false,
				'slug' => 'bar-equipment',
				'with_front' => true,
				'pages' => true,
				'ep_mask' => 1,
			),
			'query_var' => 'bar-equipment',
			'can_export' => true,
			'delete_with_user' => false,
			'taxonomies' => 
			array(
			),
		),
		'cocktails' => 
		array(
			'labels' => 
			array(
				'name' => 'Cocktails',
				'singular_name' => 'Cocktails',
				'add_new' => 'Add new',
				'add_new_item' => 'Neue cocktails hinzufügen',
				'edit_item' => 'cocktails bearbeiten',
				'new_item' => 'cocktails hinzufügen',
				'view_item' => 'cocktails anzeigen',
				'view_items' => 'Cocktails anzeigen',
				'search_items' => 'Cocktails durchsuchen',
				'not_found' => 'Kein Cocktail gefunden',
				'not_found_in_trash' => 'No cocktails found in trash',
				'parent_item_colon' => 'Übergeordnet Cocktails:',
				'all_items' => 'Alle cocktails',
				'archives' => 'Cocktail Rezepte',
				'attributes' => 'cocktails attributes',
				'insert_into_item' => 'Insert into cocktails',
				'uploaded_to_this_item' => 'Upload to this cocktails',
				'featured_image' => 'Featured image für diesen Cocktail',
				'set_featured_image' => 'Set featured image for this cocktails',
				'remove_featured_image' => 'Remove featured image for this cocktails',
				'use_featured_image' => 'Use as featured image for this cocktails',
				'filter_items_list' => 'Filter cocktails list',
				'filter_by_date' => 'Nach Datum filtern',
				'items_list_navigation' => 'cocktails list navigation',
				'items_list' => 'cocktails list',
				'item_published' => 'cocktails published',
				'item_published_privately' => 'cocktails published privately.',
				'item_reverted_to_draft' => 'cocktails reverted to draft.',
				'item_trashed' => 'Die Seite wurde in den Papierkorb verschoben.',
				'item_scheduled' => 'cocktails scheduled',
				'item_updated' => 'cocktails updated.',
				'item_link' => 'Seitenlink',
				'item_link_description' => 'Ein Link zu einer Seite.',
				'menu_name' => 'Cocktails',
				'name_admin_bar' => 'Cocktails',
				'template_name' => 'Einzelnes Element: Cocktails',
			),
			'description' => 'Bist du Durstig und auf der Suche nach einem leckeren Cocktail Rezept? Dann bist du hier genau richtig! Wir haben die besten von leckersten Cocktail Rezepte aus der ganzen Welt. Ganz gleich, ob du einen klassischen Cocktail, einen Punsch für eine Party oder ein originelles Gebräu suchst. Wir haben ein Cocktail für jeden Geschmack und Anlass, einfach nur schütteln, umrühren oder wegschütten.',
			'public' => true,
			'publicly_queryable' => true,
			'exclude_from_search' => false,
			'hierarchical' => true,
			'show_ui' => true,
			'show_in_menu' => true,
			'show_in_nav_menus' => true,
			'show_in_admin_bar' => true,
			'show_in_rest' => true,
			'rest_base' => false,
			'rest_namespace' => 'wp/v2',
			'menu_position' => 3,
			'menu_icon' => 'dashicons-admin-post',
			'capability_type' => 'post',
			'map_meta_cap' => true,
			'supports' => 
			array(
				0 => 'title',
				1 => 'author',
				2 => 'comments',
				3 => 'editor',
				4 => 'revisions',
				5 => 'thumbnail',
				6 => 'custom-fields',
				7 => 'autosave',
			),
			'has_archive' => 'cocktails',
			'rewrite' => 
			array(
				'feeds' => false,
				'slug' => 'cocktails',
				'with_front' => true,
				'pages' => true,
				'ep_mask' => 1,
			),
			'query_var' => 'cocktails',
			'can_export' => true,
			'delete_with_user' => false,
			'taxonomies' => 
			array(
				0 => 'post_tag',
				1 => 'anlass',
				2 => 'art',
				3 => 'herkunft',
			),
		),
		'trinkspiele' => 
		array(
			'labels' => 
			array(
				'name' => 'Trinkspiele',
				'singular_name' => 'Trinkspiel',
				'add_new' => 'Hinzufügen',
				'add_new_item' => 'Trinkspiel hinzufügen',
				'edit_item' => 'Trinkspiel bearbeiten',
				'new_item' => 'Neues Trinkspiel',
				'view_item' => 'Trinkspiel ansehen',
				'view_items' => 'Trinkspiele ansehen',
				'search_items' => 'Trinkspiel suchen',
				'not_found' => 'Kein Trinkspiel gefunden',
				'not_found_in_trash' => 'Kein Trinkspiel im Müll gefunden',
				'parent_item_colon' => 'Parent Trinkspiel:',
				'all_items' => 'Alle Trinkspiele',
				'archives' => 'Trinkspiel Archiv',
				'attributes' => 'Trinkspiel attributes',
				'insert_into_item' => 'Insert into Trinkspiel',
				'uploaded_to_this_item' => 'Upload to this Trinkspiel',
				'featured_image' => 'Trinkspiel Thumbnail',
				'set_featured_image' => 'Trinkspiel Thumbnail festlegen',
				'remove_featured_image' => 'Trinkspiel Thumbnail entfernen',
				'use_featured_image' => 'Als Thumbnail verwenden.',
				'filter_items_list' => 'Filter Cocktails list',
				'filter_by_date' => 'Nach Datum filtern',
				'items_list_navigation' => 'Trinkspiel list navigation',
				'items_list' => 'Trinkspiel list',
				'item_published' => 'Trinkspiel veröffentlicht',
				'item_published_privately' => 'Trinkspiel published privately.',
				'item_reverted_to_draft' => 'Trinkspiel reverted to draft.',
				'item_trashed' => 'Die Seite wurde in den Papierkorb verschoben.',
				'item_scheduled' => 'Trinkspiel geplant',
				'item_updated' => 'Trinkspiel updated.',
				'item_link' => 'Seitenlink',
				'item_link_description' => 'Ein Link zu einer Seite.',
				'menu_name' => 'Trinkspiele',
				'name_admin_bar' => 'Trinkspiel',
				'template_name' => 'Einzelnes Element: Trinkspiel',
			),
			'description' => 'Trinkspiele sind ein beliebter Zeitvertreib bei Menschen jeden Alters. Sie werden seit Tausenden von Jahren von Menschen aller Altersgruppen genossen. Vor allem aber bei Studenten und Jugendlichen. Wir haben einige der beliebtesten Trinkspiele gesammelt, die du mit deinen Freunden spielen kannst.',
			'public' => true,
			'publicly_queryable' => true,
			'exclude_from_search' => false,
			'hierarchical' => true,
			'show_ui' => true,
			'show_in_menu' => true,
			'show_in_nav_menus' => true,
			'show_in_admin_bar' => true,
			'show_in_rest' => true,
			'rest_base' => false,
			'rest_namespace' => 'wp/v2',
			'menu_position' => 5,
			'menu_icon' => 'dashicons-admin-post',
			'capability_type' => 'post',
			'map_meta_cap' => true,
			'supports' => 
			array(
				0 => 'title',
				1 => 'author',
				2 => 'comments',
				3 => 'editor',
				4 => 'revisions',
				5 => 'page-attributes',
				6 => 'thumbnail',
				7 => 'custom-fields',
				8 => 'post-formats',
				9 => 'autosave',
			),
			'has_archive' => 'trinkspiele',
			'rewrite' => 
			array(
				'feeds' => false,
				'slug' => 'trinkspiele',
				'with_front' => true,
				'pages' => true,
				'ep_mask' => 1,
			),
			'query_var' => 'trinkspiele',
			'can_export' => true,
			'delete_with_user' => false,
			'taxonomies' => 
			array(
			),
		),
	),
	'taxonomies' => 
	array(
		'anlass' => 
		array(
			'labels' => 
			array(
				'name' => 'Anlässe',
				'singular_name' => 'Anlass',
				'search_items' => 'Anlässe suchen',
				'popular_items' => 'Beliebte Anlässe',
				'all_items' => 'Alle Anlässe',
				'parent_item' => NULL,
				'parent_item_colon' => NULL,
				'name_field_description' => 'Der Name ist das, was auf deiner Website angezeigt wird.',
				'slug_field_description' => 'Die &#8222;Titelform&#8220; ist die lesbare URL-Variante des Namens. Sie besteht normalerweise nur aus Kleinbuchstaben, Zahlen und Bindestrichen.',
				'parent_field_description' => NULL,
				'desc_field_description' => 'Die Beschreibung wird standardmäßig nicht angezeigt, kann aber bei einigen Themes angezeigt werden.',
				'edit_item' => 'Anlass bearbeiten',
				'view_item' => 'Anlass anzeigen',
				'update_item' => 'Anlass aktualisieren',
				'add_new_item' => 'Neu hinzufügen: Anlass',
				'new_item_name' => 'Neuer Anlass-Name',
				'separate_items_with_commas' => 'Trenne anlässe durch Kommas',
				'add_or_remove_items' => 'anlässe hinzufügen oder entfernen',
				'choose_from_most_used' => 'Wähle aus den meistgenutzten anlässe',
				'not_found' => 'anlässe konnten nicht gefunden werden',
				'no_terms' => 'Keine anlässe-Taxonomien',
				'filter_by_item' => NULL,
				'items_list_navigation' => 'Anlässe-Listen-Navigation',
				'items_list' => 'Anlässe-Liste',
				'most_used' => 'Meistgenutzt',
				'back_to_items' => '← Zu anlässe gehen',
				'item_link' => 'Anlass-Link',
				'item_link_description' => 'Ein Link zu einer Taxonomie anlass',
				'menu_name' => 'Anlässe',
				'name_admin_bar' => 'Anlass',
				'archives' => 'Alle Anlässe',
				'template_name' => 'Anlass-Archiv',
			),
			'description' => '',
			'public' => true,
			'publicly_queryable' => true,
			'hierarchical' => false,
			'show_ui' => true,
			'show_in_menu' => true,
			'show_in_nav_menus' => true,
			'show_in_rest' => true,
			'rest_base' => false,
			'rest_namespace' => 'wp/v2',
			'show_admin_column' => false,
			'show_tagcloud' => true,
			'show_in_quick_edit' => true,
			'rewrite' => 
			array(
				'with_front' => true,
				'hierarchical' => false,
				'ep_mask' => 0,
				0 => '',
				'slug' => 'anlass',
			),
			'query_var' => 'anlass',
			'object_type' => 
			array(
				0 => 'cocktails',
			),
		),
		'art' => 
		array(
			'labels' => 
			array(
				'name' => 'Arten',
				'singular_name' => 'Art',
				'search_items' => 'Arten durchsuchen',
				'popular_items' => 'Beliebte Arten',
				'all_items' => 'Alle Arten',
				'parent_item' => NULL,
				'parent_item_colon' => NULL,
				'name_field_description' => 'Der Name ist das, was auf deiner Website angezeigt wird.',
				'slug_field_description' => 'Die &#8222;Titelform&#8220; ist die lesbare URL-Variante des Namens. Sie besteht normalerweise nur aus Kleinbuchstaben, Zahlen und Bindestrichen.',
				'parent_field_description' => NULL,
				'desc_field_description' => 'Die Beschreibung wird standardmäßig nicht angezeigt, kann aber bei einigen Themes angezeigt werden.',
				'edit_item' => 'Art bearbeiten',
				'view_item' => 'Art anzeigen',
				'update_item' => 'Update Art name',
				'add_new_item' => 'Neue Art hinzufügen',
				'new_item_name' => 'Neuer Art Name',
				'separate_items_with_commas' => 'Arten mit Kommas trennen',
				'add_or_remove_items' => 'Arten hinzufügen oder entfernen',
				'choose_from_most_used' => 'Aus den am häufigsten verwendeten Arten auswählen',
				'not_found' => 'No Arten found',
				'no_terms' => 'No Arten',
				'filter_by_item' => NULL,
				'items_list_navigation' => 'Arten list navigation',
				'items_list' => 'Arten list',
				'most_used' => 'Meistgenutzt',
				'back_to_items' => 'Back to Arten',
				'item_link' => 'Art-Link',
				'item_link_description' => 'Ein Link zu einer Taxonomie art',
				'menu_name' => 'Arten',
				'name_admin_bar' => 'Art',
				'archives' => 'Alle Arten',
				'template_name' => 'Art-Archiv',
			),
			'description' => '',
			'public' => true,
			'publicly_queryable' => false,
			'hierarchical' => false,
			'show_ui' => true,
			'show_in_menu' => true,
			'show_in_nav_menus' => true,
			'show_in_rest' => true,
			'rest_base' => false,
			'rest_namespace' => 'wp/v2',
			'show_admin_column' => false,
			'show_tagcloud' => true,
			'show_in_quick_edit' => true,
			'rewrite' => 
			array(
				'with_front' => true,
				'hierarchical' => false,
				'ep_mask' => 0,
				0 => '',
				'slug' => 'art',
			),
			'query_var' => false,
			'object_type' => 
			array(
				0 => 'cocktails',
			),
		),
		'herkunft' => 
		array(
			'labels' => 
			array(
				'name' => 'Herkunften',
				'singular_name' => 'Herkunft',
				'search_items' => 'Herkunften durchsuchen',
				'popular_items' => 'Beliebte herkunft',
				'all_items' => 'Alle Herkunften',
				'parent_item' => 'Übergeordnet Herkunft',
				'parent_item_colon' => 'Übergeordnet Herkunft:',
				'name_field_description' => 'Der Name ist das, was auf deiner Website angezeigt wird.',
				'slug_field_description' => 'Die &#8222;Titelform&#8220; ist die lesbare URL-Variante des Namens. Sie besteht normalerweise nur aus Kleinbuchstaben, Zahlen und Bindestrichen.',
				'parent_field_description' => NULL,
				'desc_field_description' => 'Die Beschreibung wird standardmäßig nicht angezeigt, kann aber bei einigen Themes angezeigt werden.',
				'edit_item' => 'Herkunft bearbeiten',
				'view_item' => 'Herkunft anzeigen',
				'update_item' => 'Update Herkunft name',
				'add_new_item' => 'Neue Herkunft hinzufügen',
				'new_item_name' => 'Neuer Herkunft Ort',
				'separate_items_with_commas' => 'Herkunft mit Kommas trennen',
				'add_or_remove_items' => 'Herkunft hinzufügen oder entfernen',
				'choose_from_most_used' => 'Aus den am häufigsten verwendeten Herkunften auswählen',
				'not_found' => 'No herkunft found',
				'no_terms' => 'Keine Herkunft',
				'filter_by_item' => NULL,
				'items_list_navigation' => 'Herkunft list navigation',
				'items_list' => 'Herkunft list',
				'most_used' => 'Meistgenutzt',
				'back_to_items' => 'Back to herkunft',
				'item_link' => 'Schlagwort-Link',
				'item_link_description' => 'Ein Link zu einem Schlagwort.',
				'menu_name' => 'Herkunft',
				'name_admin_bar' => 'Herkunft',
				'archives' => 'Alle Herkunften',
				'template_name' => 'Herkunft-Archiv',
			),
			'description' => '',
			'public' => false,
			'publicly_queryable' => false,
			'hierarchical' => false,
			'show_ui' => true,
			'show_in_menu' => true,
			'show_in_nav_menus' => true,
			'show_in_rest' => true,
			'rest_base' => false,
			'rest_namespace' => 'wp/v2',
			'show_admin_column' => false,
			'show_tagcloud' => true,
			'show_in_quick_edit' => true,
			'rewrite' => 
			array(
				'with_front' => true,
				'hierarchical' => false,
				'ep_mask' => 0,
				0 => '',
				'slug' => 'herkunft',
			),
			'query_var' => false,
			'object_type' => 
			array(
				0 => 'cocktails',
			),
		),
	),
);
